import type { Tokens } from "./tokens.schema.js";

export interface CodegenOutput {
  css: string;
  ts: string;
}

function kebabKey(path: string[]): string {
  return path.map((s) => s.replace(/_/g, "-")).join("-");
}

function resolveColor(
  value: unknown,
  all: Record<string, unknown>,
): { light: string; dark: string } {
  if (typeof value === "string") return { light: value, dark: value };
  if (value && typeof value === "object") {
    const v = value as Record<string, unknown>;
    if ("ref" in v && typeof v.ref === "string") {
      const [cat, key] = v.ref.split(".");
      const ref = (all[cat] as Record<string, unknown> | undefined)?.[key];
      return resolveColor(ref, all);
    }
    if ("light" in v && "dark" in v)
      return { light: String(v.light), dark: String(v.dark) };
  }
  return { light: "oklch(50% 0 0)", dark: "oklch(50% 0 0)" };
}

export function generateCss(tokens: Tokens): string {
  const lines: string[] = [":root {"];
  const dark: string[] = ["@media (prefers-color-scheme: dark) { :root {"];

  const allColors = tokens.color as unknown as Record<string, unknown>;
  for (const group of ["brand", "neutral", "semantic"] as const) {
    for (const [key, val] of Object.entries(
      allColors[group] as Record<string, unknown>,
    )) {
      const { light, dark: d } = resolveColor(val, allColors);
      const name = `--color-${group}-${kebabKey([key])}`;
      lines.push(`  ${name}: ${light};`);
      dark.push(`  ${name}: ${d};`);
    }
  }

  for (const [key, val] of Object.entries(tokens.space))
    lines.push(`  --space-${key}: ${val};`);
  for (const [key, val] of Object.entries(tokens.radius))
    lines.push(`  --radius-${key}: ${val};`);
  for (const [key, val] of Object.entries(tokens.shadow))
    lines.push(`  --shadow-${key}: ${val};`);
  for (const [key, val] of Object.entries(tokens.motion.duration))
    lines.push(`  --duration-${key}: ${val};`);
  for (const [key, val] of Object.entries(tokens.motion.easing))
    lines.push(`  --ease-${key}: ${val};`);

  lines.push("}");
  dark.push("}}");
  return [lines.join("\n"), dark.join("\n")].join("\n\n");
}

export function generateTs(tokens: Tokens): string {
  return [
    "// Generated by @atelier/tokens. Do not edit by hand.",
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`,
    "export type Tokens = typeof tokens;",
  ].join("\n");
}

export function generate(tokens: Tokens): CodegenOutput {
  return { css: generateCss(tokens), ts: generateTs(tokens) };
}
