import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: { default: "Brand", template: "%s · Brand" },
  description: "Brand template generated by Atelier.",
  metadataBase: new URL("https://example.com"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 focus:rounded focus:bg-[color:var(--color-brand-primary)] focus:px-3 focus:py-2 focus:text-[color:var(--color-bg)]"
        >
          Skip to content
        </a>
        <main id="main">{children}</main>
      </body>
    </html>
  );
}
